### ISSUE TITLE
The demo isn't working.

### ISSUE THREAD

**Issue by ramwin** [lepture/captcha#10]
[#24#wangx@wangxiang-PC:~]$cat test.py
from io import BytesIO
from captcha.image import ImageCaptcha

image = ImageCaptcha(fonts=['/usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf', '/usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-R.ttf'])

data = image.generate('1234')
assert isinstance(data, BytesIO)
image.write('1234', 'out.png')
[#25#wangx@wangxiang-PC:~]$python3 test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    data = image.generate('1234')
  File "/usr/local/lib/python3.4/dist-packages/captcha/image.py", line 40, in generate
    im = self.generate_image(chars)
  File "/usr/local/lib/python3.4/dist-packages/captcha/image.py", line 220, in generate_image
    self.create_noise_curve(im, color)
  File "/usr/local/lib/python3.4/dist-packages/captcha/image.py", line 132, in create_noise_curve
    Draw(image).arc(points, start, end, fill=color)
  File "/usr/lib/python3/dist-packages/PIL/ImageDraw.py", line 164, in arc
    self.draw.draw_arc(xy, start, end, ink)
TypeError: must be sequence of length 4, not 2

My environment:
ubuntu 14.04
Python 3.4.0
PIL 1.1.7

**Comment by sinmaystar** [comment]
@ramwin  @lepture  I meet the same problem with you, did u solve this problem?

**Comment by wil3** [comment]
@ramwin @sinmaystar Duplicate, see here https://github.com/lepture/captcha/issues/7

**Comment by ramwin** [comment]
Last time I tried this, I was using a computer in my previous company. Since I had changed my job, I can't reappear the environment. I tried this in ubuntu 16.04, python3.5.2 with captcha-0.2.1, it worked. Thank you for your help.
