### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by camel007** [lepture/captcha#12]
It has memory leak

**Comment by lepture** [comment]
yes?

**Comment by camel007** [comment]
![screenshot from 2016-07-21 09 18 52](https://cloud.githubusercontent.com/assets/4254753/17008607/5c12bc82-4f25-11e6-945b-113fb77d746f.png)
![screenshot from 2016-07-21 09 24 52](https://cloud.githubusercontent.com/assets/4254753/17008612/630eb1d0-4f25-11e6-9386-e646ee139489.png)

**Comment by camel007** [comment]
image.py  line 205  lambda表达式
每次调用都要生成一个table，我把table拿到外边，内存就不会涨了！
你好像会汉语，我直接写了中文

**Comment by lepture** [comment]
@camel007 可以发一个 PR
