### ISSUE TITLE
How to generate the CAPTCHA in the same size?

### ISSUE THREAD

**Issue by yuyang2009** [lepture/captcha#14]
This lib is great to generate the CAPTCHA images. But the images' sizes seem is random. Is there a way to generate the images in the same size?

**Comment by lepture** [comment]
They are in the same size. https://github.com/lepture/captcha/blob/master/captcha/image.py#L103

**Comment by yuyang2009** [comment]
Thanks @lepture , I have seen the code. It seems they are in the same size. There may be something wrong with the "numpy". The images become random size when I transform them to "ndarry".
![img](https://cloud.githubusercontent.com/assets/21993843/21632743/17acd068-d284-11e6-8ebd-db8fdf4031d5.png)

**Comment by ypwhs** [comment]
I have the same question.

https://github.com/lepture/captcha/blob/master/captcha/image.py#L166-L168

It is not always in the same size. @lepture

**Comment by lepture** [comment]
@ypwhs Can you create a test case to reproduce it?

**Comment by ypwhs** [comment]
```python
from captcha.image import ImageCaptcha
import random

generator = ImageCaptcha(width=160, height=60)
for i in range(1000):
    random_num = str(random.randint(1000, 9999))
    img = generator.generate_image(random_num)
    if img.size != (160, 60):
        print img.size
```

![snip20170218_6](https://cloud.githubusercontent.com/assets/10473170/23093879/44fe7206-f629-11e6-9e07-88ea287350be.png)

**Comment by jinji-hanbin** [comment]
@ypwhs 解决了吗？这个验证码大小问题

**Comment by eromoe** [comment]
Due to this  `captcha.image  line 200`:  `width = max(text_width, self._width)`
I have made a pull request https://github.com/lepture/captcha/pull/17

**Comment by lepture** [comment]
@eromoe 0.2.3 is released.
