### ISSUE TITLE
ImageCaptcha incomplete

### ISSUE THREAD

**Issue by jinji-hanbin** [lepture/captcha#15]
In the test environment is complete, the online environment is not complete
![image](https://cloud.githubusercontent.com/assets/18417846/24487606/66f98632-1543-11e7-8fe5-2aea8566fdb7.png)
captcha==0.2.1

**Comment by jinji-hanbin** [comment]
I am Chinese

**Comment by lepture** [comment]
same as https://github.com/lepture/captcha/issues/14 ?

**Comment by jinji-hanbin** [comment]
No, the same code, the local no problem, there is a problem online

**Comment by jinji-hanbin** [comment]
![image](https://cloud.githubusercontent.com/assets/18417846/24488324/a66a4374-1548-11e7-85fb-a9bd3af36ae7.png)
![image](https://cloud.githubusercontent.com/assets/18417846/24488333/b208680a-1548-11e7-925b-9ab4e51d7364.png)

**Comment by jinji-hanbin** [comment]
@lepture

**Comment by lepture** [comment]
@jinji-hanbin make `font_sizes` smaller. e.g.

```
ImageCaptcha(font_sizes=(22, 24, 26))
```
