### ISSUE TITLE
image cut (missing/truncated letters)

### ISSUE THREAD

**Issue by sctt** [lepture/captcha#22]
hello,
i like this library a lot and i'm using it in my projects.
the only recurring problem i have is this:
sometimes (not very often, but also not very rarely), the generated captcha image cannot be fully read because the last letter is missing or truncated.
i tried with different combinations of fonts and number of characters, to set an acceptable wider static image width (250px for a 7 chars string) but that problem is still occuring.
sometimes, but more rarely, letters are also truncated on their lower part.
those problems happen when generated letters are too high, too wide or too spaced.

are you aware of that issue? any tip to fix or work around it?

thank you.

**Comment by shispt** [comment]
I'm facing the same issue. Here is my result:
```python
ImageCaptcha(width=250, height=100).write('euix', 'test.png')
```
![test](https://github.com/lepture/captcha/assets/4241969/5db6412c-1edb-4a4f-b33b-afdfb1949dde)

**Comment by TruncatedDinosour** [comment]
i think this increases the security of the captcha but this library is a bit painful overall if u want fine control over captcha, i encourage to create ur own if ur still facing this issue in 2024 almost ( from an issue tht was made in 2017 lol )

**Comment by lepture** [comment]
You can use a larger size.
