### ISSUE TITLE
Can't install captcha in Python 3.5

### ISSUE THREAD

**Issue by zhangzhanqicixi** [lepture/captcha#32]
I use command: `pip3 install captcha `
The exception info: Could not find a version that satisfies the requirement captcha (from versions: )
No matching distribution found for captcha

So the captcha module can't support Python3?

**Comment by matthias4217** [comment]
I can install it fine with Python3.6. Maybe it has something to do with captcha's requirements ?

**Comment by lepture** [comment]
Fixed.
