### ISSUE TITLE
No module named captcha.audio

### ISSUE THREAD

**Issue by MurphyLee2048** [lepture/captcha#35]
Requirement already satisfied: captcha in /usr/local/lib/python3.6/dist-packages (0.3)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from captcha) (5.1.0)
limu2048@ubuntu:~$ cd /usr/local/lib/python3.6/dist-packages
limu2048@ubuntu:/usr/local/lib/python3.6/dist-packages$ ls
captcha
captcha-0.3.dist-info
---------------------------
I think I  successfully  install captcha?
But when I import it, it shows the error info below:
---------------------------------------------------------
No module named captcha.audio
------------------------
Can you help me? I'm new to python and I've stuck in this problem for a day.

**Comment by lepture** [comment]
Not sure what’s wrong with the provided description.
