### ISSUE TITLE
How to run test or demo?

### ISSUE THREAD

**Issue by vanloc0301** [lepture/captcha#4]
I'm download in and install with command:

`python setup.py install`

It create folder `lib`, `captcha.egg-info` and `dist`.
I'm run `captcha-master\build\lib\captcha` with command:

`python audio.py out.wav`

But not show anything.

Thank you very much.

**Comment by lepture** [comment]
@vanloc0301 There is no script to generate a wave file. If you want to create a wave file, follow the **Usage** section:

https://github.com/lepture/captcha#usage

**Comment by lepture** [comment]
ping.. will close in next week.
