### ISSUE TITLE
Numbers "Seven" and "One" have the same view

### ISSUE THREAD

**Issue by vikingUnet** [lepture/captcha#40]
Hello! Is there are simple way to change generation of number "Seven" to look different way then number "One"? My users fall into longing))

**Comment by lepture** [comment]
@vikingUnet That depends on your "Font". You can switch to a font that you can tell the difference between 7 and 1 easily.

Another option is that, you normalize 7 and 1 into one character. For e.g.

```py
def save_into_cache(captch_chars):
    captch_chars = captch_chars.replace('7', '1')
    cache.save(captch_chars)
```

And verify the input:

```py
def verifier_input(input):
    input = input.replace('7', '1')
    saved = cache.get()
    return input == saved
```

**Comment by vikingUnet** [comment]
Yes, i simply normalized '7' to '1', but i think, that decision case with changing font is more right way, just little bit difficult fore me. Thanks for answer!!
