### ISSUE TITLE
Voice sources

### ISSUE THREAD

**Issue by raneq** [lepture/captcha#42]
You may be interested in the CC0-licensed Mozilla's [Common Voice](https://voice.mozilla.org/ca/datasets).

> Each entry in the dataset consists of a unique MP3 and corresponding text file. Many of the 4,257 recorded hours in the dataset also include demographic metadata like age, sex, and accent that can help train the accuracy of speech recognition engines. The dataset currently consists of 3,401 validated hours in 40 languages, but we’re always adding more voices and languages. Take a look at our Languages page to request a language or start contributing.

[Forvo](https://forvo.com) too has a huge dataset of pronounced words and sentences, but they are not as eager as Mozilla to share it.

**Comment by peppelinux** [comment]
simple as possibile, customizable (let's prevent machine learning...) 

````
for i in {a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9}; do mkdir it-$i; cd it-$i ;espeak -v it -w $i.wav; cd ..; done
````

**Comment by peppelinux** [comment]
here
https://github.com/lepture/captcha/pull/43

**Comment by lepture** [comment]
Added here:

https://captcha.lepture.com/audio/#voice-library
