### ISSUE TITLE
How can i  not change font shape?

### ISSUE THREAD

**Issue by XMISSM** [lepture/captcha#48]
How can i  not change font shape?

**Comment by dshaw0004** [comment]
Do you mean same font size for all characters?

**Comment by XMISSM** [comment]
来信已收到,会尽快查看,谢谢!

**Comment by dshaw0004** [comment]
> 来信已收到,会尽快查看,谢谢!

English please

**Comment by TruncatedDinosour** [comment]
> > 来信已收到,会尽快查看,谢谢!
> 
> English please

lol its 'The letter has been received and will be checked as soon as possible. Thank you!'

**Comment by XMISSM** [comment]
来信已收到,会尽快查看,谢谢!

**Comment by XMISSM** [comment]
来信已收到,会尽快查看,谢谢!
