### ISSUE TITLE
No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by ivgenib** [lepture/captcha#53]
When using with Django framework >= 2.0, the module 'django.core.urlresolvers' does noto exist:
https://stackoverflow.com/questions/43139081/importerror-no-module-named-django-core-urlresolvers

File "\site-packages\captcha\fields.py", line 4, in <module>
    from django.core.urlresolvers import reverse, NoReverseMatch
ModuleNotFoundError: No module named 'django.core.urlresolvers'

The import should be changed with:
    from django.urls import reverse, NoReverseMatch

**Comment by lepture** [comment]
I think you are asking in the wrong place. We have no django related code.

**Comment by ivgenib** [comment]
The issue is with the package django-simple-captcha, which are installed in the same path as this package. Update to latest django-simple-captcha to resolve the issue.
