### ISSUE TITLE
New version without deprecation warnings about Pillow 10

### ISSUE THREAD

**Issue by ilBEastli** [lepture/captcha#61]
Would you mind to release the next version with commits that already exists in the master branch (e9047d5d2ce1def459db111ccc1e8ea38bb9425b, f1ad88403fd892836dba93d829871fd40635a063, 10a464cc786dd19457c2c859e6391e95557d0995)? 🙏🏻

**Comment by ilBEastli** [comment]
@lepture, forgot to mention you in the original post 🙂

**Comment by lepture** [comment]
Released.
