### ISSUE TITLE
Captcha giving errors with new Pillow release

### ISSUE THREAD

**Issue by MVARUNREDDY8203** [lepture/captcha#64]
With new release of Pillow (ver 10) its giving 
AttributeError: 'ImageDraw' object has no attribute 'textsize'
I tried using an older version of Pillow, but captcha by default downloads the latest version so you cant use it.

![image](https://github.com/lepture/captcha/assets/94187286/520899bd-17cc-49e5-b357-43e221549d40)

**Comment by mycollectingbox** [comment]
I reinstall old version of Pillow, and error is gone.
pip install --force-reinstall -v "Pillow==9.2.0"

**Comment by MVARUNREDDY8203** [comment]
tried installing older versions, but still is giving some sort of errors

**Comment by MVARUNREDDY8203** [comment]
I actually tried fixing the captcha _draw_character(c): in image.py, , since this was throwing the error, I went to pillow docs, I couldnt find any textsize() method, instead there was a textlength() method, tried changing textsize() to textlength() in my local captcha image.py file and running, was getting some other error, so gotta move on, but other contributors, lemme know if you need help.

**Comment by mycollectingbox** [comment]
> tried installing older versions, but still is giving some sort of errors

But, you mean the error is due to new release of Pillow.
I just use generate(self, chars, format='png') function

**Comment by MVARUNREDDY8203** [comment]
its working now yea
