### ISSUE TITLE
TypeError when running image example

### ISSUE THREAD

**Issue by wil3** [lepture/captcha#7]
Trace:

......
    data = image.generate('1234')
  File "/usr/local/lib/python2.7/dist-packages/captcha/image.py", line 40, in generate
    im = self.generate_image(chars)
  File "/usr/local/lib/python2.7/dist-packages/captcha/image.py", line 219, in generate_image
    self.create_noise_curve(im, color)
  File "/usr/local/lib/python2.7/dist-packages/captcha/image.py", line 132, in create_noise_curve
    Draw(image).arc(points, start, end, fill=color)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 164, in arc
    self.draw.draw_arc(xy, start, end, ink)
TypeError: must be sequence of length 4, not 2

**Comment by intlabs** [comment]
I am seeing the same issue, did you manage to solve it?

**Comment by lepture** [comment]
Could you show me the dependencies?

**Comment by wil3** [comment]
@intlabs I did not, ended up using a different implementation http://www.pythonbackend.com/topic/1434357520

@lepture This is from the readme example, which dependencies are you referring too? Heres my output from pip list

adium-theme-ubuntu (0.3.4)
apt-xapian-index (0.45)
argparse (1.2.1)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.2.1)
blinker (1.4)
boto (2.38.0)
captcha (0.2)
ccsm (0.9.11.3)
certifi (2015.9.6.2)
cffi (1.2.1)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
compizconfig-python (0.9.11.3)
ConfigArgParse (0.9.3)
cryptography (1.0)
cvxopt (1.1.4)
debtagshw (0.1)
decorator (3.4.0)
defer (1.0.6)
dirspec (13.10)
duplicity (0.6.23)
enum34 (1.0.4)
gyp (0.1)
hpack (1.1.0)
html2text (2015.6.21)
html5lib (0.999)
httplib2 (0.8)
idna (2.0)
ipaddress (1.0.14)
ipython (1.2.1)
Jinja2 (2.7.2)
joblib (0.7.1)
lockfile (0.8)
lxml (3.4.4)
MarkupSafe (0.18)
matplotlib (1.3.1)
mitmproxy (0.13)
MySQL-python (1.2.3)
netlib (0.13.1)
nose (1.3.1)
numexpr (2.2.2)
numpy (1.8.2)
oauthlib (0.6.1)
oneconf (0.3.7)
openpyxl (1.7.0)
otpauth (1.0.1)
PAM (0.4.2)
pandas (0.13.1)
passlib (1.6.5)
patsy (0.2.1)
pexpect (3.1)
Pillow (2.3.0)
pip (1.5.4)
piston-mini-client (0.7.5)
pyasn1 (0.1.8)
pycparser (2.14)
pycrypto (2.6.1)
pycups (1.9.66)
pycurl (7.19.3)
pygobject (3.12.0)
pyOpenSSL (0.15.1)
pyparsing (2.0.1)
pyperclip (1.5.11)
pyserial (2.6)
pysmbc (1.0.14.1)
pystache (0.5.4)
python-apt (0.9.3.5ubuntu1)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2012c)
pyutil (2.0.0)
pyxdg (0.25)
pyzmq (14.0.1)
reportlab (3.0)
requests (2.2.1)
scipy (0.13.3)
sessioninstaller (0.0.0)
setuptools (3.3)
simplegeneric (0.8.1)
simplejson (3.3.1)
simpy (3.0.8)
six (1.5.2)
software-center-aptd-plugins (0.0.0)
SQLAlchemy (1.0.8)
statsmodels (0.5.0)
sympy (0.7.4.1)
system-service (0.1.6)
tables (3.1.1)
tornado (4.2.1)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
unity-lens-photos (1.0)
urllib3 (1.7.1)
urwid (1.3.0)
vboxapi (1.0)
wheel (0.24.0)
wsgiref (0.1.2)
xdiagnose (3.6.3build2)
xlrd (0.9.2)
xlwt (0.7.5)
z-base-36 (1.0.1)
zbase32 (1.1.5)
zope.interface (4.0.5)

**Comment by lepture** [comment]
@wil3 upgrade Pillow

This package used `draw_arc` function of Pillow:

```
File "/usr/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 164, in arc
self.draw.draw_arc(xy, start, end, ink)
```

**Comment by wil3** [comment]
So heres what I had to do to get the example running. installing pillow will fail without libjpeg-dev. The example will fail without compiling Pillow with libfreetype

```
sudo apt-get install libfreetype6-dev
sudo apt-get install libjpeg-dev
sudo pip uninstall Pillow
sudo pip install -U Pillow
```

The libfreetype error can be reference here https://github.com/python-pillow/Pillow/issues/1375

However there is now a new issue, the assertion fails:

```
assert isinstance(data, BytesIO)
```

If you uncomment this out it works. The actual type of data is 
```
<type 'cStringIO.StringO'>
```
