### ISSUE TITLE
Why not work?

### ISSUE THREAD

**Issue by smohe1991** [lepture/captcha#8]
error:
raise importerror("the _imagingft c module is not installed")

**Comment by smohe1991** [comment]
please help me...

**Comment by lepture** [comment]
http://pillow.readthedocs.org/en/latest/installation.html

http://pillow.readthedocs.org/en/latest/installation.html#external-libraries

**Comment by lepture** [comment]
ping... solved?

**Comment by haspagan** [comment]
I met the same problem while using the "generate" method from imageCaptcha as shown in the example. The solution, on Debian Jessie, was to install the libfreetype6-dev package, uninstall Pillow from pip and reinstall it (with the  --no-cache-dir option but it might be useless). I'm late to the party but I hope it could be of some help.
