### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by lmzlmz** [lepture/captcha#9]
I run the demo(just the ImageCaptcha part) and it works fine to generate a captcha. But there's an AssertionError when I run "data = image.generate('1234')".

**Comment by lepture** [comment]
Can't guess what happened with your information

**Comment by lmzlmz** [comment]
from io import BytesIO
from captcha.image import ImageCaptcha

image = ImageCaptcha()

data = image.generate('1234')
assert isinstance(data, BytesIO)

-------------------------------------------------
When I run codes above, I get the AssertionError. Apparently, 'data' is not a BytesIO object.

**Comment by khowarizmi** [comment]
@lmzlmz  just remove this line `assert isinstance(data, BytesIO)`

**Comment by lepture** [comment]
Oh... I've removed `assert` from readme.
